# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weathermail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.DateTimeField(verbose_name='history date')),
                ('temperature', models.FloatField(verbose_name='history temperature')),
                ('weather', models.CharField(max_length=100, null=True)),
                ('icon_url', models.URLField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weathermail.PopulousCity')),
            ],
            options={
                'ordering': ('history_date',),
            },
        ),
    ]
